export const GET_EVENT_TODAY = "GET_EVENT_TODAY";
export const GET_EVENT_UPCOMING = "GET_EVENT_UPCOMING";
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const EVENT_BY_CATEGORY = "EVENT_BY_CATEGORY";
